### ISSUE TITLE
Slicing Profile dropdown doesn't have any profiles (after completing Import Profiles... )

### ISSUE THREAD

**Issue by b-morgan** [Garr-R/OctoPrint-Slicer#4] opened 2024-03-20 18:35 UTC
I imported a profile (see issue #1) and uploaded an .stl file. I am attempting to slice but the Slicing Profile is empty and clicking the dropdown shows nothing.

![image](https://github.com/Garr-Garr/OctoPrint-InternalSlicer/assets/1547854/9963e8b9-1344-4350-aaf4-627de721b01e)

**Comment by Garr-Garr** [comment] 2024-03-20 18:40
This may be related to your previous bug report ~ not sure at the moment. 
Is slicing still disabled after refreshing the page?

**Comment by Garr-Garr** [comment] 2024-03-20 18:51
closing duplicate bug report ~ the issue is related to the LuzBot profile

**Closed as completed by Garr-Garr** 2024-03-20 18:51 UTC
